// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dujxppzkotxrxlfzzobz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1anhwcHprb3R4cnhsZnp6b2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODU5NTksImV4cCI6MjA1OTY2MTk1OX0.hG6MVfvnCjuaz1EtlEibvSBwYRc8euWjvYNogxQmHSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);